sonar.projectKey=jojiiikol_devops_labs
sonar.organization=jojiiikol

sonar.qualitygate.wait=false

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=devops_labs
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=backend,Frontend
sonar.exclusions=backend/tests/**, \
  \ Frontend/coverage/**,\
  \ Frontend/src/test/**,\
  \ Frontend/server.test.js, \
  \ **/*.test.ts,\
  \ **/*.test.tsx,\
  \ **/*.spec.ts,\
  \ **/*.spec.tsx

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=Frontend/coverage/lcov.info

sonar.coverage.exclusions=Frontend/src/main.tsx