apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 10Gi