apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas:
    1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/api/metrics"
    spec:
      containers:
        - name: backend
          image: jojiiikol/note-backend:f628b435add08f87187045bfd188d65e12451d53
          ports:
            - containerPort: 8000
            - name: metrics
              containerPort: 8000
          resources:
            limits:
              cpu: "500m"
            requests:
              cpu: "250m"
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_HOST
            - name: DB_PORT
              value: "5432"
            - name: AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AUTH_SECRET_KEY
            - name: HOST_IP
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: HOST_IP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15