apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: jojiiikol/note-frontend:c22a615284dc866ab0daf1f085c47b176fc1b742
          ports:
            - containerPort: 3000
