name: build-test_CI
on:
  push:
    paths:
      - 'backend/**'
      - 'Frontend/**'
      - '.github/workflows/**'
jobs:

  sonar-scanner:
    name: SonarQube Scanner
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            backend
            Frontend

      - name: python_install
        uses: actions/setup-python@v6
        with:
          python-version: '3.9.12'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -e py

      - name: node_install
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: install_deps
        run: npm ci
        working-directory: Frontend

      - name: Coverage
        run: npm run test:coverage
        working-directory: Frontend

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  backend:
    needs: [ sonar-scanner ]
    uses: ./.github/workflows/backend-workflow.yaml

  backend-docker:
    needs: [ sonar-scanner, backend ]
    uses: ./.github/workflows/backend-docker.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  frontend:
    needs: [ sonar-scanner, backend, backend-docker ]
    uses: ./.github/workflows/frontend_workflow.yaml

  frontend-docker:
    needs: [ sonar-scanner, backend, frontend, backend-docker ]
    uses: ./.github/workflows/frontend-docker.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
