name: frontend-docker
on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      VITE_API_BASE_URL:
        required: true
      TELEGRAM_TOKEN:
        required: true
      TELEGRAM_TO:
        required: true

jobs:
  frontend-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      -
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            Frontend
      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/note-frontend:${{ github.sha }}
          build-args: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
      -
        name: Notify Telegram
        if: always()
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *Job:* `frontend-docker`
            *Status:* `${{ job.status }}`
            *Workflow:* `${{ github.workflow }}`
            *Branch:* `${{ github.ref_name }}`
            *Commit:* `${{ github.sha }}`
            *Run:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
